# Generated by Django 5.0.4 on 2024-04-05 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('age', models.IntegerField()),
                ('gender', models.BooleanField(choices=[(1, '男'), (2, '女')])),
                ('id_card', models.CharField(max_length=18)),
                ('address', models.CharField(max_length=255)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'permissions': (),
            },
        ),
    ]
